### GET all users
GET http://localhost:8080/users
Accept: application/json

### GET all adult users
GET http://localhost:8080/users/adults
Accept: application/json

### GET all users within age range
GET http://localhost:8080/users/age/1/30
Accept: application/json

### GET all users containing in name
GET http://localhost:8080/users?name="Bauters"
Accept: application/json